export default googleMapConfig = {
  IOS_GOOGLE_MAPS_APIKEY: 'AIzaSyBwINjstRC_Slxjj8s1HnS7k__4y5J3OQ8', //'AIzaSyDk7EZN9jJBPvKeth5TvmxqOKdHB_UrX78',
  ANDROID_GOOGLE_MAPS_APIKEY: 'AIzaSyCBn6cZU4C8V8AG0HtZNcUk5U1FpGMPQr8'
}