export const RENT_INIT = 'rent/RENT_INIT';
export const RENT_REQUEST = 'rent/RENT_REQUEST';
export const RENT_SUCCESS = 'rent/RENT_SUCCESS';
export const RENT_FAILURE = 'rent/RENT_FAILURE';
export const RENT_RETURNED_BATTERY = 'rent/RENT_RETURNED_BATTERY';
export const RENT_RETURNED_BATTERY_FAILED = 'rent/RENT_RETURNED_BATTERY_FAILED';
export const RENT_REQUIRED_FEEDBACK = 'rent/RENT_REQUIRED_FEEDBACK';